env:
    global:
        - secure: "LY/9M98qx113HEAH6DbY8J5bpYYp3ElUWhcKWqYMQ9JD+1dshEEwiWh0PmY/krcLt/v2fzSFy22XmmjbOThkjG65UdpHSDdbnricesDmi0kWdd9gsBKhQWkur3sWKtL8TPdJAXXKD0iO9qKsDbbbKmNdmZtxsCqQWn3gpjbRIeo="
        - secure: "Ln9TGZ7PN5KYyrbC82w4V6d+9XI/5g+bOYZ0/kHhh/hDI57odiotgIDG9WxPCB8LGF2KCXyxbRWkCtKe3Bh16wrCFBBzH8ojIRzEtP1UznRXyKIS/mWGIsSLzIDNWpBFhMBpzwgc6ltgLVhuXQv8f6lkgeUZq6fwkf4sQ6BT8JE="
        - secure: "YIVjXjLNrxbNbzjtDj78vAE4OILjQa3UQGlrEoLz2LqjH0kcgMNLPno+gqPh6ePB5QVO74A9khJMnXnjiJOF3nkw368FLvEE9XeJ0LVDlfPWt3VtTN5XAtFDOoxnJ1floLZjdbzDNNBR5bi+xOXu7lri7rFfTQhE20DNPaEOp6U="

before_script:
    - git config --global user.email $GIT_EMAIL
    - git config --global user.name $GIT_NAME

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq ruby
    - sudo apt-get install -qq xsltproc fop
    - gem install jekyll

script:
    - git clone "https://${GH_TOKEN}@github.com/${GIT_NAME}/cf-convention.github.io.git"
    - cd cf-convention.github.io
    # Should we build cf-conventions-1.6 too?
    - cd Data/cf-conventions/cf-conventions-1.7
    - mkdir docbooktmp
    - make
    - git commit build -m "Auto-generated HTML"
    - cd ../../..
    - jekyll build
    # NOTE: All this could eventually become a generate.sh script.

after_success:
    # Publish it!
    - git push --force
